import type { Metadata } from 'next';
import styles from './layout.module.css';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Footer, Header, Sidebar } from './components';
import { Up } from '@/components';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ru" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className={styles.body}>
        <Header className={styles.header}>
          <Sidebar className={styles.sidebarMobile} />
        </Header>
        <Sidebar className={styles.sidebar} />
        <main className={styles.main}>{children}</main>
        <Footer className={styles.footer} />
        <Up />
      </body>
    </html>
  );
}
